export const CHALLENGES = [
  {
    id: 1,
    authorId: 1,
    type: 1,
    dateStart: '21/04/2017',
    dateEnd: '21/06/2017',
    title: 'Chocapic',
    summary: 'Prends un bain dans une piscine de Chicapic',
  },
  {
    id: 2,
    authorId: 1,
    type: 2,
    dateStart: '05/04/2017',
    dateEnd: '10/06/2017',
    title: 'Orange is the new pink',
    summary: 'Fais un selfie avec une Barbie relookée en Donald Trump',
  },
  {
    id: 3,
    authorId: 1,
    type: 2,
    dateStart: '01/04/2017',
    dateEnd: '01/07/2017',
    title: 'Héééééé ma-ca-re-na',
    summary: 'Crée la meilleure pose digne de Fauve Hautot avec ton chat. Ou celui de la voisine.',
  },
  {
    id: 4,
    authorId: 2,
    type: 1,
    dateStart: '11/04/2017',
    dateEnd: '21/09/2017',
    title: 'Georges',
    summary: 'Balance toi sur une liane et fonce dans un tronc (attention à ne pas te faire mal ;))',
  },
  {
    id: 5,
    authorId: 3,
    type: 1,
    dateStart: '05/04/2017',
    dateEnd: '01/01/2018',
    title: 'Say my name',
    summary: 'Deviens le meilleur Walter White',
  },
  {
    id: 6,
    authorId: 2,
    type: 2,
    dateStart: '01/02/2017',
    dateEnd: '01/03/2017',
    title: 'Banana',
    summary: 'Crée la meilleure équipe de Minions',
  },
  {
    id: 7,
    authorId: 5,
    type: 1,
    dateStart: '21/04/2017',
    dateEnd: '21/06/2017',
    title: 'Attrapez-les tous !',
    summary: 'Prends un bain dans une piscine de Chicapic',
  },
  {
    id: 8,
    authorId: 3,
    type: 2,
    dateStart: '05/04/2017',
    dateEnd: '10/06/2017',
    title: 'C\'est mon ami et bien plus encore',
    summary: 'Fais un selfie avec une Barbie relookée en Donald Trump',
  },
  {
    id: 9,
    authorId: 2,
    type: 2,
    dateStart: '01/04/2017',
    dateEnd: '01/07/2017',
    title: 'Mojito',
    summary: 'Crée la meilleure pose digne de Fauve Hautot avec ton chat. Ou celui de la voisine.',
  },
  {
    id: 10,
    authorId: 2,
    type: 1,
    dateStart: '11/04/2017',
    dateEnd: '21/09/2017',
    title: 'Vol au dessus d\'un nid de coucous',
    summary: 'Balance toi sur une liane et fonce dans un tronc (attention à ne pas te faire mal ;))',
  },
  {
    id: 11,
    authorId: 3,
    type: 1,
    dateStart: '05/04/2017',
    dateEnd: '01/01/2018',
    title: 'La balade des gens heureux',
    summary: 'Deviens le meilleur Walter White',
  },
  {
    id: 12,
    authorId: 2,
    type: 2,
    dateStart: '01/02/2017',
    dateEnd: '01/03/2019',
    title: 'Citrons et pommes de pin',
    summary: 'Crée la meilleure équipe de Minions',
  },
];

export const USERS = {
  1: {
    id: 1,
    username: 'missimac',
    score: 14,
  },
  2: {
    id: 2,
    username: 'Teapot',
    score: 350,
  },
  3: {
    id: 3,
    username: 'Hector',
    score: 4,
  },
  4: {
    id: 4,
    username: 'frisette',
    score: 41,
  },
  5: {
    id: 5,
    username: 'Schlomo',
    score: 1,
  },
};
